# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_message_pb2 as chat__message__pb2


class ChatMessagesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.unary_stream(
                '/grpc.ChatMessages/ChatStream',
                request_serializer=chat__message__pb2.User.SerializeToString,
                response_deserializer=chat__message__pb2.ChatMessage.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/grpc.ChatMessages/SendMessage',
                request_serializer=chat__message__pb2.ChatMessage.SerializeToString,
                response_deserializer=chat__message__pb2.RequestSuccess.FromString,
                )
        self.SendUserInformation = channel.unary_unary(
                '/grpc.ChatMessages/SendUserInformation',
                request_serializer=chat__message__pb2.User.SerializeToString,
                response_deserializer=chat__message__pb2.User.FromString,
                )
        self.SendUserRegistration = channel.unary_unary(
                '/grpc.ChatMessages/SendUserRegistration',
                request_serializer=chat__message__pb2.UserLogin.SerializeToString,
                response_deserializer=chat__message__pb2.RequestSuccess.FromString,
                )
        self.CheckUserLogin = channel.unary_unary(
                '/grpc.ChatMessages/CheckUserLogin',
                request_serializer=chat__message__pb2.UserLogin.SerializeToString,
                response_deserializer=chat__message__pb2.RequestSuccess.FromString,
                )
        self.GetKnownUsers = channel.unary_unary(
                '/grpc.ChatMessages/GetKnownUsers',
                request_serializer=chat__message__pb2.User.SerializeToString,
                response_deserializer=chat__message__pb2.UserArray.FromString,
                )
        self.LoadOldMessages = channel.unary_stream(
                '/grpc.ChatMessages/LoadOldMessages',
                request_serializer=chat__message__pb2.Chat.SerializeToString,
                response_deserializer=chat__message__pb2.ChatMessage.FromString,
                )
        self.DeleteProfile = channel.unary_unary(
                '/grpc.ChatMessages/DeleteProfile',
                request_serializer=chat__message__pb2.UserLogin.SerializeToString,
                response_deserializer=chat__message__pb2.RequestSuccess.FromString,
                )
        self.GetSystemInformation = channel.unary_unary(
                '/grpc.ChatMessages/GetSystemInformation',
                request_serializer=chat__message__pb2.Empty.SerializeToString,
                response_deserializer=chat__message__pb2.SystemInformation.FromString,
                )
        self.GetSystemMetrics = channel.unary_stream(
                '/grpc.ChatMessages/GetSystemMetrics',
                request_serializer=chat__message__pb2.Interval.SerializeToString,
                response_deserializer=chat__message__pb2.Metrics.FromString,
                )
        self.GetAllUsers = channel.unary_stream(
                '/grpc.ChatMessages/GetAllUsers',
                request_serializer=chat__message__pb2.Empty.SerializeToString,
                response_deserializer=chat__message__pb2.User.FromString,
                )


class ChatMessagesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendUserInformation(self, request, context):
        """SendUserInformation sends a User but only with an userName and an userID and returns the whole stored data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendUserRegistration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKnownUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadOldMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatMessagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=chat__message__pb2.User.FromString,
                    response_serializer=chat__message__pb2.ChatMessage.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chat__message__pb2.ChatMessage.FromString,
                    response_serializer=chat__message__pb2.RequestSuccess.SerializeToString,
            ),
            'SendUserInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUserInformation,
                    request_deserializer=chat__message__pb2.User.FromString,
                    response_serializer=chat__message__pb2.User.SerializeToString,
            ),
            'SendUserRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUserRegistration,
                    request_deserializer=chat__message__pb2.UserLogin.FromString,
                    response_serializer=chat__message__pb2.RequestSuccess.SerializeToString,
            ),
            'CheckUserLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserLogin,
                    request_deserializer=chat__message__pb2.UserLogin.FromString,
                    response_serializer=chat__message__pb2.RequestSuccess.SerializeToString,
            ),
            'GetKnownUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKnownUsers,
                    request_deserializer=chat__message__pb2.User.FromString,
                    response_serializer=chat__message__pb2.UserArray.SerializeToString,
            ),
            'LoadOldMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.LoadOldMessages,
                    request_deserializer=chat__message__pb2.Chat.FromString,
                    response_serializer=chat__message__pb2.ChatMessage.SerializeToString,
            ),
            'DeleteProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProfile,
                    request_deserializer=chat__message__pb2.UserLogin.FromString,
                    response_serializer=chat__message__pb2.RequestSuccess.SerializeToString,
            ),
            'GetSystemInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInformation,
                    request_deserializer=chat__message__pb2.Empty.FromString,
                    response_serializer=chat__message__pb2.SystemInformation.SerializeToString,
            ),
            'GetSystemMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSystemMetrics,
                    request_deserializer=chat__message__pb2.Interval.FromString,
                    response_serializer=chat__message__pb2.Metrics.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=chat__message__pb2.Empty.FromString,
                    response_serializer=chat__message__pb2.User.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ChatMessages', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatMessages(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ChatMessages/ChatStream',
            chat__message__pb2.User.SerializeToString,
            chat__message__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatMessages/SendMessage',
            chat__message__pb2.ChatMessage.SerializeToString,
            chat__message__pb2.RequestSuccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendUserInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatMessages/SendUserInformation',
            chat__message__pb2.User.SerializeToString,
            chat__message__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendUserRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatMessages/SendUserRegistration',
            chat__message__pb2.UserLogin.SerializeToString,
            chat__message__pb2.RequestSuccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatMessages/CheckUserLogin',
            chat__message__pb2.UserLogin.SerializeToString,
            chat__message__pb2.RequestSuccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKnownUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatMessages/GetKnownUsers',
            chat__message__pb2.User.SerializeToString,
            chat__message__pb2.UserArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadOldMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ChatMessages/LoadOldMessages',
            chat__message__pb2.Chat.SerializeToString,
            chat__message__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatMessages/DeleteProfile',
            chat__message__pb2.UserLogin.SerializeToString,
            chat__message__pb2.RequestSuccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatMessages/GetSystemInformation',
            chat__message__pb2.Empty.SerializeToString,
            chat__message__pb2.SystemInformation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ChatMessages/GetSystemMetrics',
            chat__message__pb2.Interval.SerializeToString,
            chat__message__pb2.Metrics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ChatMessages/GetAllUsers',
            chat__message__pb2.Empty.SerializeToString,
            chat__message__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
